#
# Copyright (c) 2023, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for AP/RSS non-volatile counter platform test
#

source [file join [file dirname [info script]] handle-arguments.inc]

# Trusted Firmware boot section
source [file join [file dirname [info script]] trusted-firmware.inc]

expect_string "Starting platform tests..."

expect {
	"Platform tests failed." {
		exit_uart -1
	}
	"Platform tests succeeded." {
		exit_uart 0
	}
}

exit_uart -1
