#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
	image="kernel" type="fvp-busybox-uboot" get_boot_image
	image="initrd" type="default" get_boot_image
}

generate_lava_job_template() {
	uart="0" file="linux-rd-busybox.exp" track_expect

	payload_type="linux" gen_yaml_template
}
