#!/usr/bin/env bash
#
# Copyright (c) 2021-2023 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job(){
        if [ "${ci_env}" = "armci" ]; then
            payload_type="linux"
        else
            # Run simple boot test on OpenCi
            payload_type="boot"
        fi
        target="n1sdp" payload_type="${payload_type}" gen_yaml_template
        gen_n1sdp_yaml
}
