#!/usr/bin/env bash
#
# Copyright (c) 2021-2023 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job(){
        target="n1sdp" payload_type="linux" gen_yaml_template
        gen_n1sdp_yaml
}
