#!/usr/bin/env bash
#
# Copyright (c) 2021-2023 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

fetch_tf_resource() {
        fetch_prebuilt_fw_images
}

post_fetch_tf_resource() {
        gen_recovery_image
}
