#
# Copyright (c) 2023, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for Trusted Firmware Test Framework
#

prompt='PMF:cpu 0	tid 0'
expect_string+=("i,${prompt}")

prompt='PMF:cpu 0	tid 1'
expect_string+=("i,${prompt}")

prompt='PMF:cpu 0	tid 2'
expect_string+=("i,${prompt}")

prompt='PMF:cpu 0	tid 3'
expect_string+=("i,${prompt}")

prompt='PMF:cpu 0	tid 4'
expect_string+=("i,${prompt}")
